// Code generated by ent, DO NOT EDIT.

package attendance

const (
	// Label holds the string label denoting the attendance type in the database.
	Label = "attendance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmployeeID holds the string denoting the employee_id field in the database.
	FieldEmployeeID = "employee_id"
	// FieldClockedIn holds the string denoting the clocked_in field in the database.
	FieldClockedIn = "clocked_in"
	// FieldClockedOut holds the string denoting the clocked_out field in the database.
	FieldClockedOut = "clocked_out"
	// Table holds the table name of the attendance in the database.
	Table = "attendances"
)

// Columns holds all SQL columns for attendance fields.
var Columns = []string{
	FieldID,
	FieldEmployeeID,
	FieldClockedIn,
	FieldClockedOut,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
