app:
  host: 127.0.0.1
  port: 8080

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123
  name: attendance

smtp: 
  host: smtp.gmail.com
  port: 587

amqp: 
  host: localhost
  port: 5672