// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attendance is the predicate function for attendance builders.
type Attendance func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
